Cam port
gold2718/svn_select_to_git pull request #2
Opened 2019-07-18 22:47 UTC by nusbaume

Added modifications to allow for CESM and regression script builds in git.  I should note that I had to revert one of your changes to "configure" in order to get the regression scripts to work.  Also some of the white-spacing in the modified scripts can turn out a little wonky, but the code itself should be fine. 

Finally, just FYI, one regression test, "TFM", which checks for the validity of the subversion repo, will always fail, because obviously the repo is no longer an svn repo.  I imagine at some point we might want to replace this test with a git equivalent, but I figured that can probably wait until after the move to the cime scripts.  Of course if you think we should replace it sooner just let me know!

2019-07-19 19:02 UTC, gold2718 requested changes
Couple of minor change but I wonder if test_driver.sh is working for the wrong reasons.

2019-07-19 19:02 UTC, gold2718 commented on svn_select_to_git.py
> +               ('if [ -d \`${CAM_SCRIPTDIR}/../../components\` ]; then\n'
I believe the backtick syntax here is illegal and will generate both an error message and the wrong test result. Always use double quotes around strings in bash test expressions.

2019-07-19 19:02 UTC, gold2718 commented on svn_select_to_git.py
> +               ('if [ -n "\${CAM_ROOT}" ] && [ -f \${CAM_ROOT}/test/system/test_driver.sh ]; then\n'
For consistency, please add double quotes around the second string. Also, a cleaner bash syntax is:
```
if [ -n "\${CAM_ROOT}"  -a  -f "\${CAM_ROOT}/test/system/test_driver.sh" ]; then
```

2019-07-24 16:24 UTC, gold2718 requested changes
Please remove the TFM test. I suggest doing this by adding a pattern for tests_pretag_hobart_nag and tests_pretag_izumi_nag to remove the `fm001` line.

2019-07-24 16:26 UTC, gold2718 commented
Please add a description of the tests run to the PR description.  This should include running test/cam_test.sh and a list of tests run for both a standalone clone and a CESM-style clone.

2019-07-25 16:15 UTC, nusbaume commented
Python script tests run for latest commit:

./svn_select_to_git.py --author-table CAM_name_table.txt --tags https://svn-ccsm-models.cgd.ucar.edu/cam1/trunk_tags --rev 91300:91422 cam_trunk_svn ../cam_trunk_git https://svn-ccsm-models.cgd.ucar.edu/cam1/trunk

test/cam_test.sh

CAM tests run for latest commit:

"test/system/test_driver.sh -f" on izumi, with cam6_1_027 tag, with NAG compiler, in CAM-only framework.

"test/system/test_driver.sh -f" on hobart, with cam_cesm2_1_rel_26 tag, with NAG compiler, in CESM framework.

Also ran "test_drivers.sh -f" with ".git" removed, ".gitignore" removed, an extra ".git" file added, and in a subversion repository, to ensure that the "TGIT.sh" script behaves as expected.

2019-08-25 22:59 UTC, merged